/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.beothorn;

public class App {

    public static void main(String[] args) {
        App app = new App();
        String result = app.a();
        System.out.println(result);
    }

    private String a() {
        System.out.println("A was called");
        return "Return from A";
    }

    private String b() {
        System.out.println("B was called");
        return "Return from B";
    }
}
