/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.beothorn;

public class App {

    public static void main(String[] args) {
        String lang = System.getenv("LANG");
        String port = System.getenv("PORT");
        if (lang.equals("en_us")) {
            System.out.println("The language is english. The port is "+port);
        } else if (lang.equals("pt_br")) {
            System.out.println("A língua é português. A porta é "+port);
        } else {
            System.out.println("Unknown language "+lang+" port "+port);
        }
    }
}
