<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>br.com.isageek</groupId>
  <artifactId>bcbridge-maven-plugin-example</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>17</maven.compiler.release>
    <maven.compiler.plugin.version>3.15.0</maven.compiler.plugin.version>
    <maven.jar.plugin.version>3.5.0</maven.jar.plugin.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>${maven.jar.plugin.version}</version>
        <configuration>
          <archive>
            <manifest>
              <mainClass>br.com.isageek.bcbridge.example.App</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>br.com.isageek</groupId>
        <artifactId>bcbridge-maven-plugin</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <configuration>
          <bridges>
            <bridge>
              <sourceApplication>bcbridge-maven-plugin-example</sourceApplication>
              <source>bcbridge.example.App#defaultMatcherOriginal</source>
              <dest>br.com.isageek.bcbridge.example.App#defaultMatcherRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(namedOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#namedRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>namedIgnoreCase(BR.COM.ISAGEEK.BCBRIDGE.EXAMPLE.APP)#namedIgnoreCase(NAMEDIGNORECASEORIGINAL)</source>
              <dest>br.com.isageek.bcbridge.example.App#namedIgnoreCaseRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameStartsWith(br.com.isageek.bcbridge.example)#nameStartsWith(nameStartsWithOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#nameStartsWithRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameStartsWithIgnoreCase(BR.COM.ISAGEEK.BCBRIDGE.EXAMPLE)#nameStartsWithIgnoreCase(NAMESTARTSWITHIGNORECASEORIGINAL)</source>
              <dest>br.com.isageek.bcbridge.example.App#nameStartsWithIgnoreCaseRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameEndsWith(App)#nameEndsWith(nameEndsWithOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#nameEndsWithRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameEndsWithIgnoreCase(APP)#nameEndsWithIgnoreCase(NAMEENDSWITHIGNORECASEORIGINAL)</source>
              <dest>br.com.isageek.bcbridge.example.App#nameEndsWithIgnoreCaseRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameContains(bcbridge.example)#nameContains(ContainsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#nameContainsRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameContainsIgnoreCase(BCBRIDGE.EXAMPLE)#nameContainsIgnoreCase(CONTAINSIGNORECASEORIGINAL)</source>
              <dest>br.com.isageek.bcbridge.example.App#nameContainsIgnoreCaseRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>nameMatches(br[.]com[.]isageek[.]bcbridge[.]example[.]App)#nameMatches(nameMatchesOrigina[l])</source>
              <dest>br.com.isageek.bcbridge.example.App#nameMatchesRedirected</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(redirectArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#redirectArgumentsDestination</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(redirectNoArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#redirectNoArgumentsDestination</dest>
              <type>redirect</type>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(redirectThisOnlyOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#redirectThisOnlyDestination</dest>
              <type>redirect</type>
              <thisAsParameter>true</thisAsParameter>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(redirectThisAndArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#redirectThisAndArgumentsDestination</dest>
              <type>redirect</type>
              <captureArguments>args</captureArguments>
              <thisAsParameter>true</thisAsParameter>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(enterArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#enterArgumentsDestination</dest>
              <type>OnMethodEnter</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(enterNoArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#enterNoArgumentsDestination</dest>
              <type>OnMethodEnter</type>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(enterThisOnlyOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#enterThisOnlyDestination</dest>
              <type>OnMethodEnter</type>
              <thisAsParameter>true</thisAsParameter>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(enterThisAndArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#enterThisAndArgumentsDestination</dest>
              <type>OnMethodEnter</type>
              <captureArguments>args</captureArguments>
              <thisAsParameter>true</thisAsParameter>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(exitArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#exitArgumentsDestination</dest>
              <type>OnMethodExit</type>
              <captureArguments>args</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(exitNoArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#exitNoArgumentsDestination</dest>
              <type>OnMethodExit</type>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(exitThisOnlyOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#exitThisOnlyDestination</dest>
              <type>OnMethodExit</type>
              <thisAsParameter>true</thisAsParameter>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(exitThisAndArgumentsOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#exitThisAndArgumentsDestination</dest>
              <type>OnMethodExit</type>
              <captureArguments>args</captureArguments>
              <thisAsParameter>true</thisAsParameter>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(redirectArrayOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#redirectArrayDestination</dest>
              <type>redirect</type>
              <captureArguments>array</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(enterArrayOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#enterArrayDestination</dest>
              <type>OnMethodEnter</type>
              <captureArguments>array</captureArguments>
            </bridge>
            <bridge>
              <source>named(br.com.isageek.bcbridge.example.App)#named(exitArrayOriginal)</source>
              <dest>br.com.isageek.bcbridge.example.App#exitArrayDestination</dest>
              <type>OnMethodExit</type>
              <captureArguments>array</captureArguments>
            </bridge>
          </bridges>
        </configuration>
        <executions>
          <execution>
            <id>bcbridge</id>
            <phase>package</phase>
            <goals>
              <goal>rewrite</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
